## NUMPY

1. It is a core python library used     for  numerical computation 

2. It is built for handling  large arrays and matrices effeciently.

3. It is faster than python built in lists because it uses c language style storage where actual values are stored at contiguous location (not object references).

## It contain :

**ndarray object**: N-dimensional array for fast numerical operations.

**Vectoriszed operations**: Perform element_wise calculations without loops.

**broadcasting**: Operate on arraya of different shapes

**Linear algebra functions**: Matrix operations like multiplication and inversion 

**Statistical function**: Mean , median , stadard deviation .

**Integration**: Works with Pandas, Scipy and scikit_learn.


## Why to learn numpy 

1. Excutes vectorized operations 10 to 100 times faster than standar Python loops.

2. Uses homogeneous arrays to store large datasets more compactly than python lists.

3. Provide otimized functions for linear algebra, Fourier transforms an matrix manipulations.

4. Includes robust tools for statistics, random number generation and missing data managmenet.

5. Expresses complex math in single-line commands,eliminating the need for manual, nested loops.

## Types of array 

**One dimensional array**





In [2]:
import numpy as np 
a=[1,2,3,4,5,6]
arr= np.array(a)
print("list in python:",a)
print("numy array in python:",arr)



list in python: [1, 2, 3, 4, 5, 6]
numy array in python: [1 2 3 4 5 6]


## Multi-Dimensional Array




In [14]:
import numpy as np 

list_1 =[1,2,3,4,5,6,7,8]
list_2 =[6,4,6,3,6,8,2,4]
list_3 =[2,5,6,7,9,88,4,5]

arr = np.array([list_1,list_2,list_3])
print("numpy multidimensional array:\n",arr)





numpy multidimensional array:
 [[ 1  2  3  4  5  6  7  8]
 [ 6  4  6  3  6  8  2  4]
 [ 2  5  6  7  9 88  4  5]]


## Parameters of Numpy Array

1. **Axis**: Describe the order of the indexing into the array.

Axis 0 = One dimensional
Axis 1 = Two dimensional
Axis 2 = Three dimensional

2. **Shape**: No. of elements along with each axis and is returned as a tuple.


In [21]:
import numpy as np 
arr = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [19,23,34,4,56]])
print("shape of an array:",arr.shape)




shape of an array: (3, 5)


3. **Rank**: no. of axes or dimensions it has.

one dimension array as 1 rank 
two dimension array has 2 rank 

4. **Data type objects(dtype)**: it is an example of numpy.dtype class

It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.



In [22]:
import numpy as np 
arr_1= np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])
print("Data type of an array 1:",arr_1.dtype)

print("Data type of array:",arr_2.dtype)


Data type of an array 1: int64
Data type of array: int64


## Different ways of creating a numpy

**numpy.fromiter()**: create a new one dimensional array from an iterable object.

**Syntax**: numpy.fromiter(iterable,dtype,count=-1)


we can also use generator to create array in numpy .

## Creating a numpy array from unicode 

 You have to use U2 as it represent unicode string with a fixed length of 2 characters 

 **U indicates that the datatype in unicode and the number '2' specifies the length of each string .**

In [ ]:
import numpy as np 
a = [1,2,3,4,5,6,7,8,9]
arr = np.fromiter(a,dtype=int)
print(a)

## creating a numpy array generated by generator expression in python 

b=(x**3 for x in range(3))
arr_1 = np.fromiter(b,int)
print(arr_1)

## square of number 0 to 5 

c = (x**2 for x in range(6))
arr_2 = np.fromiter(c, int)
print(arr_2)

# unicode

d =[70,100,100,106]
un = np.fromiter((chr(x) for x in d),dtype='U1')
print(un)

e = "python"
unicode =np.fromiter(e,dtype='U2')
print(unicode)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 8]
[ 0  1  4  9 16 25]
['F' 'd' 'd' 'j']
['p' 'y' 't' 'h' 'o' 'n']


## Numpy Arange 

numpy.arange() function create an array of evenly spaced values within a given interval 

It is similar to python built- in range()function but return a numpy array instead of a list 

## Syntax

numpy.arange(start,stop, step,dtype=None)

return type : array of evenly spaced values.



In [27]:
import numpy as np 
f = np.arange(5,10)
print(f)



g = np.arange(1,20,2, dtype = np.float32)
print(g)

[5 6 7 8 9]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


## Numpy.linspace()


It is used to generate an array of evenly spaced values between two specified numbers.

Instead of deining a step size , the total number of required value is specified and numpy automatically calculates the spacing between them .

## Parameters 
**start** : starting value (default 0)

**Stop** : ending value of range

**num** : number of values to generate 
(default 50)

**endpoint** : Includes stop if True (default True)

**restep** : return step size if True (default False)

**dtype** : Output array data type

**axis** : Axis for generation when inputs are array- like (default 0)

## Syntax 

numpy.linspace(start, stop , num=50, endpoint=True,restep=False,dtype=None, axis = 0)



In [32]:
import numpy as np 
b = np.linspace(0,1, num=10, endpoint=False)
print(b)

## Multidimensional array 

d = np.linspace(0,1,num=16).reshape(4,4)
print(d)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0.         0.06666667 0.13333333 0.2       ]
 [0.26666667 0.33333333 0.4        0.46666667]
 [0.53333333 0.6        0.66666667 0.73333333]
 [0.8        0.86666667 0.93333333 1.        ]]


## Numpy.empty()


numpy.empty(shape,dtype=float,order='c'):Return a new array of given shape and type , with random values 

## Parameters

**shape** : Number of rows 

**order** : c_contiguous or F_contiguous

**dtype** : [optional , float(by default)] Datatype of returned array.





In [35]:
import numpy as np 

b = np.empty(2,dtype = int)
print("MATRIX : \n " , b)

a = np.empty([2,2] , dtype= int)
print("\nMatrix a : \n" , a)

c= np.empty([3,3])
print("\nMatrix c : \n",c)

MATRIX : 
  [429496729670 455266533476]

Matrix a : 
 [[            0 1384249538048]
 [1384249536848 1384249537728]]

Matrix c : 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


## Numpy.ones()

return a new array of given shape and type with ones.

## Syntax 

numpy.ones(shape , dtype = None, order ='c')

## Parameters

**shape** : integer or sequence of integers

**order** : C_contiguous or F_contiguous

C- contiguous order in memory( last index varies the fastest)
C order means that operating row -wise on the array will be slightly quicker 

FORTRAN - contiguous order in memory (first index varies the fastest).

FAORDER MEANS THAT  column- wise operations will be faster .

**dtype** : [optional , float(by default)] Data type of returned array 


In [40]:
import numpy as np 

b = np.ones(2,dtype= int)
print("Matrix b: \n" ,b )

a = np.ones([2,2], dtype = int)
print(" Matrix a :\n", a)

np.ones([4,3], dtype = np.int32, order = 'f')


Matrix b: 
 [1 1]
 Matrix a :
 [[1 1]
 [1 1]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## Numpy.zeros

creates a new array of specified shapes and types , filled withzeros.



In [45]:
import numpy as np 
arr = np.zeros(5)
print(arr, end =" ")

arr_1 = np.zeros((3,4))
print(arr_1, end =" ")

# Create an array of tuples with zeros
d = np.zeros((2, 2), dtype=[('f', 'f4'), ('i', 'i4')])
print(d)



[0. 0. 0. 0. 0.] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


## np.full()

numpy.full(shape, fill_value, dtype = None, order = 'C') : Return a new array with the same shape and type as a given array filled with a fill_value. 


**Parameters :**


**shape**: Number of 

**order** : C_contiguous or F_contiguous

**dtype**: [optional, float(by Default)] Data type of returned array.  

**fill_value**: [bool, optional] Value to fill in the array.



In [46]:


import numpy as np

a = np.full([2, 2], 67, dtype = int)
print("\nMatrix a : \n", a)

c = np.full([3, 3], 10.1)
print("\nMatrix c : \n", c)


Matrix a : 
 [[67 67]
 [67 67]]

Matrix c : 
 [[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


## Create Python Numpy Arrays Using Random Number Generation


NumPy provides functions to create arrays filled with random numbers.

**np.random.rand()**: Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).

**np.random.randn()**: Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.


**np.random.randint()**: Creates an array of specified shape and fills it with random integers within a given range.






In [47]:
import numpy as np

ar = np.random.rand(2, 3)
an = np.random.randn(2, 2)
ai = np.random.randint(1, 10, size=(2, 3))  

print(ar)
print(an)
print(ai)

[[0.27250677 0.74453354 0.17445215]
 [0.08050559 0.30395162 0.81099701]]
[[-0.65786607  0.8936682 ]
 [ 1.27295395  0.45035641]]
[[4 3 7]
 [4 2 2]]


## Create Python Numpy Arrays Using Matrix Creation Routines


NumPy provides functions to create specific types of matrices.

**np.eye()**: Creates an identity matrix of specified size.

**np.diag()**: Constructs a diagonal array.

**np.zeros_like()**: Creates an array of zeros with the same shape and type as a given array.

**np.ones_like()**: Creates an array of ones with the same shape and type as a given array.

In [48]:
import numpy as np

im = np.eye(3)
da = np.diag([1, 2, 3])
a0 = np.zeros_like(da)
a1 = np.ones_like(da)

print(im)
print(da)
print(a0)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Numpy Array Indexing

Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array. This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets. In this article, we’ll see the different ways to index and slice NumPy arrays which helps us to work with our data more effectively.

## 1. Accessing Elements in 1D Arrays

A 1D NumPy array is a sequence of values with positions called indices which starts at 0. We access elements by using these indices in square brackets like arr[0] for the first element. Negative indices count from the end so arr[-1] gives the last element.



In [49]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


## 2. Accessing Elements in Multidimensional Arrays

In this we will see how to access elements in both 2D and 3D arrays using specific indices.


**2D Arrays:** We can access elements by specifying both row and column indices like matrix[row, column].








In [ ]:
import numpy as np 

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])



cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])
print (cube[0,1,2])

## index 1 start from row 1 

# cube be like : block , row column : 2 block , 3 row , 1 column  element,  another 1 block ,2 row , 3 column 



6
16
6


## 3. Slicing Arrays

It allows us to extract a range of elements using the format start:stop:step. This can be done for both 1D and multidimensional arrays which allows us to select ranges of elements or submatrices easily.

**Slicing 1D Arrays:** For a 1D array, slicing returns a subset of elements between the start and stop indices.


In [54]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

[1 2 3]


# Slicing Multidimensional Arrays: 

In this slicing can be applied to each dimension separately which allows us to extract submatrices or smaller blocks of data.

In [55]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]



## 4. Boolean 


It allows us to filter elements from an array based on a condition and returns only those that meet it. We create a boolean array from a condition and use it to select elements and can combine conditions with logical operators.


In [56]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])

## using logical operator 

arr = np.array([10, 15, 20, 25, 30])

print(arr[(arr > 10) & (arr < 30)])

[25 30]
[15 20 25]


## 5. Fancy Indexing

It is also known as Advanced Indexing which allows us access elements of an array by using another array or list of indices. This allows selecting multiple elements at once even if they are not next to each other which makes it easy to pick specific values from different positions in the array.

In [57]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


## 7. Ellipsis (...) in Indexing


The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. This is helpful in multidimensional arrays when we don’t want to specify every dimension.


Here it selects all elements in the first two dimensions and 0 selects the first element along the last dimension for each.

**Note: It will generate random number as it uses random function.**

In [58]:
import numpy as np

cube = np.random.rand(4, 4, 4)

print(cube[..., 0])

[[0.91743696 0.81334322 0.02031881 0.30641567]
 [0.18545152 0.19804163 0.65582189 0.96843542]
 [0.68329599 0.11291127 0.79897673 0.11491958]
 [0.67210302 0.47662888 0.55405173 0.2556457 ]]


# Reshape 

In [60]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3)
print(r)


b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
s = b.reshape(2, 2, 2)
print(s)

c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
t = c.reshape(3, -1)
print(t)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Resize 


In [62]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))
print(arr)


arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 4))
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


## Stacking

numpy.stack()


The numpy.stack() function is used to join multiple arrays by creating a new axis in the output array. This means the resulting array always has one extra dimension compared to the input arrays. To stack arrays, they must have the same shape, and NumPy places them along the axis you specify.

np.stack((a, b), axis=0) creates a new 0th axis and places arrays one below another.


In [63]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=0)
print(res)

[[1 2 3]
 [4 5 6]]


In [65]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))
print(np.stack((a, b), axis=-1))

'''
axis=0: a and b become rows.
axis=1: a and b become columns.
axis=-1: same as axis 1 because it refers to the last dimension.
'''

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


'\naxis=0: a and b become rows.\naxis=1: a and b become columns.\naxis=-1: same as axis 1 because it refers to the last dimension.\n'

In [66]:
# stacking in 3d 

import numpy as np

m = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

n = np.array([[[10, 20], [30, 40]],
              [[50, 60], [70, 80]]])

print(np.stack((m, n), axis=0))
print(np.stack((m, n), axis=1))
print(np.stack((m, n), axis=2))
print(np.stack((m, n), axis=3))

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [ 3  4]]

  [[10 20]
   [30 40]]]


 [[[ 5  6]
   [ 7  8]]

  [[50 60]
   [70 80]]]]
[[[[ 1  2]
   [10 20]]

  [[ 3  4]
   [30 40]]]


 [[[ 5  6]
   [50 60]]

  [[ 7  8]
   [70 80]]]]
[[[[ 1 10]
   [ 2 20]]

  [[ 3 30]
   [ 4 40]]]


 [[[ 5 50]
   [ 6 60]]

  [[ 7 70]
   [ 8 80]]]]


## splitting  in array 

Splitting arrays means dividing a single NumPy array into multiple smaller sub-arrays. NumPy provides several functions that make this easy by allowing you to split arrays along different directions (rows, columns, depth).

Below are some important terms to understand when splitting arrays:

**Axis:** The direction along which the array is split (0 for rows, 1 for columns).

**Sub-arrays:** Smaller arrays created after splitting the original array.

**Splitting Methods:** Functions like np.split(), np.hsplit(), np.vsplit() and np.array_split().

**Equal vs. Unequal Splits:** Splits can divide data evenly, or slightly unevenly if needed (using array_split()).

In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


## Splitting methods 

1. numpy.split()

2. numpy.array_split()

3. numpy.vsplit()

4. numpy.hsplit()

5. numpy.dsplit() : it is majorly used in  matrix staking , it is  used for 3D arrays. It splits the array along the third axis (axis=2). This is useful when working with stacked matrices, images, or multi-channel data.



In [68]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))
res = np.dsplit(arr, 2)
print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


## Broadcasting

Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops.

## Working of Broadcasting in NumPy

Broadcasting applies specific rules to find whether two arrays can be aligned for operations or not that are:

**Check Dimensions:** Ensure the arrays have the same number of dimensions or expandable dimensions.

**Dimension Padding:** If arrays have different numbers of dimensions the smaller array is left-padded with ones.

**Shape Compatibility:**Two dimensions are compatible if they are equal or one of them is 1.
If these conditions aren’t met NumPy will raise a ValueError

In [70]:
#Broadcasting a Scalar to a 1D Array


import numpy as np
arr = np.array([1, 2, 3])
res = arr + 1  
print(res)

#Broadcasting a 1D Array to a 2D Array


a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)


[2 3 4]
[[ 3  7 11]
 [ 9 13 17]]


In [71]:
# Broadcasting in Conditional Operations

import numpy as np

a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [72]:
#  Using Broadcasting for Matrix Multiplication

import numpy as np
m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])
res = m * v
print(res)

[[10 40]
 [30 80]]


## Centering Data in Machine Learning

Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by subtracting the mean from each feature. This example centers each feature by subtracting its mean using NumPy broadcasting.

In [73]:
import numpy as np

data = np.array([ [10, 20],
                  [15, 25],
                  [20, 30] ])

m = data.mean(axis=0)
res = data - m
print(res)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


## NumPy - Arithmetic Operations



In [ ]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.add(a, b)
r = np.subtract(a, b)
s = np.multiply(a,b)
u = np.divide(a,b)
print(res)
print(r)
print(s)
print(u)





[  7  77  23 130]
[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]
