## PyTorch 


**PyTorch** is a Python based  deep learning library that run on CPU by default and supports GPU acceleration using CUDA.


It follows a define -by run approach, creating dynamic  computation graphs during execution , which makes debugging and customization easier .

Uses dynamic graphs for flexibility
provides automatic differentiation for gradient computation

Supports GPU acceleration with CUDA



In [1]:
pip install torch torchvision torchaudio

  Using cached torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Using cached torch-2.12.0-cp313-cp313-win_amd64.whl (123.0 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.1 MB 1.7 MB/s eta 0:00:03
   ----- ---------------------------------- 0.5/4.1 MB 1.7 MB/s eta 0:00:03
   ------- -------------------------------- 0.8/4.1 MB 771.1 kB/s eta 0:00:05
   ---------- ----------------------------- 1.0/4.1 MB 908.5 kB/s eta 0:00:04
   ------------ --------------------------- 1.3/4.1 MB 1.0 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.1 MB 1.1 MB/s eta 0:00:03
   ----------------- ---------------------- 1.8/4.1 MB 1.2 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.1 MB 1.1 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.1 MB 1.1 MB/s eta 0:00:02
   -------------------- ----------------


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Pytorch can be installed on windows using pip for CPU(without GPU)


To install PyTorch in Jupyter notebook or google colab:

In [2]:
! pip install torch torchvision torchaudio


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## PyTorch Tensors

A PyTorch Tensor is basically the same as NumPy array. This means it does not know anything about deep learning or computational graphs or graadient and is just a generic n-dimensional array to be used for arbitrary numeric computation.

The biggest difference between a NumPy array and PyTorch is that a PyTorch  Tensor can run on either on CPU or GPU 

To run  operations on the GPU , just cast the Tensor to a cuda datatype using 

device = torch.device("cpu")


# to create random input and output data ,


# and H is hidden dimension; D_out is output dimension.


N, D_in, H, D_out = 32, 100, 10, 2 


x = torch.randn(N, D_in, device=device, dtype=torch.float)    #where x is a tensor 



# how to create a tensor 

In [4]:
import torch 


In [5]:
v_data =[1,2,3,4,5]
v = torch.tensor(v_data)
print(v)

tensor([1, 2, 3, 4, 5])


In [7]:
x = torch.randn((3,4,5))
print(x)

tensor([[[ 0.0565, -2.0079,  1.7717,  0.4861, -0.2525],
         [ 1.2994, -0.3431,  0.3200, -0.0119,  1.9235],
         [ 0.0732, -0.5179,  2.1757, -1.2454, -1.2554],
         [-1.3592,  0.2420, -0.9739, -0.2086,  0.6495]],

        [[-1.4448,  0.3103, -0.5463, -1.0776,  1.0452],
         [ 0.3147, -0.2500,  0.5839, -0.9929, -1.0360],
         [ 0.7878, -0.1259, -0.7167,  0.5046,  0.6507],
         [ 0.0494, -0.3654, -1.3759,  0.6711, -1.3196]],

        [[-1.9711,  0.2069,  0.1434, -1.4060, -1.6109],
         [-1.1625, -0.6208, -0.7286,  1.8903, -1.9133],
         [ 0.6270,  2.1063,  0.5021, -0.7419, -1.3865],
         [ 0.0826,  1.4903, -1.4865, -1.5967, -0.6473]]])


create a tensor of random data with a given dimensionality .


# create new tensor with all elements , initalized as zeros

In [12]:
z= torch.zeros([3,3])

#z= torch.zeros([3,3],dtype=torch.int32)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
torch.ones([3,3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**torch.full()** and **torch.full_like()**:  These functions return a Tensor of the required size filled with required fill_value provided. The complete prototype for **torch.full()** is:

**Syntax:** torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)



#  torch.full_like() is:

**Syntax:** torch.full_like(input, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)

In [18]:
torch.full((4,3),2.15)

tensor([[2.1500, 2.1500, 2.1500],
        [2.1500, 2.1500, 2.1500],
        [2.1500, 2.1500, 2.1500],
        [2.1500, 2.1500, 2.1500]])

In [24]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor,end="\n\n")

x = torch.full_like(newTensor,3.24, dtype=None )
print(x)



tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])

tensor([[3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400],
        [3.2400, 3.2400, 3.2400]])


# Tensor attributes


each **tensor** (torch.Tensor) has a 

torch.dtype , torch.device , torch.layout

PyTorch has 12 different datatypes 

torch.device is an object represnting the device on which a torch.Tensor will be allocated.

torch.layout object which represent that memory layout of a torch.Tensor

torch support 2 type of memory  layout 

**torch.strided:** represent dense Tensor and the most commonly used memory layout.

each stridden tensor has an associated torch.Storage, which holds its data.

The stride of an array (also called as increment , pitch or step size) is the number of locations in memory between the beginnings of successive array elements, measures in bytes or in units of the size of the array elements. 

the stride  cannot be smaller tahn the element sie but  can be larger . 

indicating extra space between elements .

In [28]:
x= torch.tensor([[1,2,3,4,4,5,6,6],[1,2,3,4,5,6,7,8]])
x.stride()

(8, 1)

 **torch.sparse_coo_tensor**

used to store array in the sparse coordinate list.

COO format, the specified elements are stored as tuples of element indices and the corresponding values.

In [31]:
i = [[0, 1, 1],
     [2, 0, 2]]

v =  [3, 4, 5]
a = torch.sparse_coo_tensor(i, v, (2, 3))
print(a)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)


# Tensor Operations

In [55]:
x = torch.tensor([1,2,3,4,5,6])
y = torch.tensor([2,3,4,5,6,7])
print(x+y)
print(torch.matmul(x,y))



tensor([ 3,  5,  7,  9, 11, 13])
tensor(112)


In [43]:
x = torch.randn(2,5)
y = torch.randn(2,5)
print (torch.cat([x,y]), end ="\n\n")
print(torch.cat([x,y],1))

tensor([[ 0.7179, -0.9988,  1.2955, -0.5766,  0.3689],
        [ 0.3019,  0.0276, -0.6145,  0.4880,  2.5206],
        [ 1.1655,  1.1825,  0.8035, -0.1412,  0.0458],
        [-0.1788, -1.5997, -0.1499,  1.0372,  0.1228]])

tensor([[ 0.7179, -0.9988,  1.2955, -0.5766,  0.3689,  1.1655,  1.1825,  0.8035,
         -0.1412,  0.0458],
        [ 0.3019,  0.0276, -0.6145,  0.4880,  2.5206, -0.1788, -1.5997, -0.1499,
          1.0372,  0.1228]])


# view()  can reshape the tensors using .view method()

In [45]:
x = torch.randn(1,3,4)
print(x)

#print(x.view(2,12))


tensor([[[-0.6234,  0.3615,  0.8970,  0.6039],
         [-0.1034,  1.1911, -1.2554,  0.0234],
         [-1.0965,  0.4406,  0.0695,  0.9358]]])


In [50]:
x = torch.randn(2,3,4)
print(x, end="\n\n")

print(x.view(2,12))


tensor([[[-0.7946, -1.0917,  0.4872, -1.6518],
         [ 1.4234,  0.0378, -0.5620,  1.4435],
         [-1.5901, -0.1594, -0.2591, -0.8769]],

        [[ 1.6830,  0.0936,  1.1905, -0.0661],
         [ 0.7018, -0.3660, -0.5027, -1.8278],
         [-0.0963, -0.7302, -0.1769, -1.8241]]])

tensor([[-0.7946, -1.0917,  0.4872, -1.6518,  1.4234,  0.0378, -0.5620,  1.4435,
         -1.5901, -0.1594, -0.2591, -0.8769],
        [ 1.6830,  0.0936,  1.1905, -0.0661,  0.7018, -0.3660, -0.5027, -1.8278,
         -0.0963, -0.7302, -0.1769, -1.8241]])


**torch.argmax()** returns the index of the maximum value of all element in the input tensor.

In [53]:
x = torch.randn(3,3)
print((x,torch.argmax(x)))

(tensor([[-1.5464,  0.9301, -0.0130],
        [ 1.6415,  0.3322,  2.5503],
        [-0.2035,  0.2073,  0.1774]]), tensor(5))


In [54]:
x = torch.randn(3,3)
print((x, torch.argmin(x)))

(tensor([[ 0.0081,  0.4851,  1.5082],
        [-1.4079, -0.2973,  1.0850],
        [ 0.2550,  0.7766,  0.0253]]), tensor(3))


# Autograd & Computational Graphs

Autograd module automates gadient calculation for backpropagation

In [62]:
x = torch.tensor(2.0,requires_grad = True)
y= x**2
y.backward()
print(x.grad)


tensor(4.)


PyTorch Dynamically creates a computational grapgh that tracks operations and gradients for backpropagation.

**In Pytorch, neural ntworks are built using the torch.nn module**

**torch.nn.Parameter** is a subclass of **torch.tensor**.

it is designed specifically for holding parameters in a model that should be considered during training.

when a tensor is wrapped with **torch.nn.Parameter** , it automatically becomes a part of the model's parameters , and thus it will be updated when backpropagation is applied during training.

this is fundamental because it tells PyTorch's optimizer which tensor should be updated through learning processes.

## Key Features of torch.nn.Parameter


**Trainable Parameters**: By default , parameters wrapped in torch.nn.Parameter are considered trainable.

means they are part of the model's learnable parameters and are subject to updates during gradient descent 

**Integration with odules:** models are typically built using the torch.nn.Module class . Any torch.nn.Parameter assigned as an attribute to a module is automatically registered as a paramter of the module.

**Easy Serialization:** Parameters can be easily saved along with other model components using PyTorch's serialization tools, making it easy to save and load trained models.


# Usage of torch.nn.parameter

In [64]:
import torch
import torch.nn as nn

class MyLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super(MyLinear, self).__init__()
        # Define weight and bias parameters
        self.weight = nn.Parameter(torch.randn(out_features, in_features))
        self.bias = nn.Parameter(torch.randn(out_features))

    def forward(self, x):
        # Implement the forward pass
        return torch.matmul(x, self.weight.t()) + self.bias

In this example, **self.weight**and **self.bias** are instances of **torch.nn.Parameter**. During training, these parameters will be updated to minimize the loss function, thanks to their registration as module parameters.

# Guide to train  a model with torch.nn.Parameter

# Import necessary libraries


In [65]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the neural network Class

In [66]:
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        # Define a parameter (weight) using torch.nn.Parameter
        self.weight = nn.Parameter(torch.randn(1, requires_grad=True))
        
    def forward(self, x):
        # Apply the weight to the input
        return x * self.weight

# Instantiate the model 

Create an instance of SimpleNet. Print the initial model parameters to verify that the weight has been initialized.

In [69]:
#Instantiate the model
model = SimpleNet()
print("Initial Model Parameters:", list(model.parameters()))

Initial Model Parameters: [Parameter containing:
tensor([-1.3700], requires_grad=True)]


# Set up Loss Function  and Optimizer


Define the loss function and optimizer for training. Here, we use the Mean Squared Error (MSE) loss and Stochastic Gradient Descent (SGD) optimizer.

In [70]:
# Define a loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)




# Prepare Training Data 


Define the input and target tensors. These tensors represent the data that the model will learn from during training.

In [71]:
# Sample input and target
input_tensor = torch.tensor([2.0])
target_tensor = torch.tensor([4.0])

# Train the Model 

Execute the training loop. This loop involves forwarding pass, loss calculation, backpropagation, and parameter updates. Monitor the training progress by printing the loss and current weight every 10 epochs.

In [72]:
# Training loop
for epoch in range(100):
    optimizer.zero_grad()  # Zero the gradients
    output = model(input_tensor)  # Forward pass
    loss = criterion(output, target_tensor)  # Compute loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update parameters

    if epoch % 10 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item()}, Weight: {model.weight.item()}')

Epoch 0, Loss: 45.42804718017578, Weight: -1.1004153490066528
Epoch 10, Loss: 8.571969032287598, Weight: 0.6532153487205505
Epoch 20, Loss: 1.61747407913208, Weight: 1.414972186088562
Epoch 30, Loss: 0.3052067458629608, Weight: 1.745870590209961
Epoch 40, Loss: 0.057590506970882416, Weight: 1.8896090984344482
Epoch 50, Loss: 0.01086695957928896, Weight: 1.9520474672317505
Epoch 60, Loss: 0.0020504924468696117, Weight: 1.9791700839996338
Epoch 70, Loss: 0.0003869186621159315, Weight: 1.990951657295227
Epoch 80, Loss: 7.301568984985352e-05, Weight: 1.996069312095642
Epoch 90, Loss: 1.3776720152236521e-05, Weight: 1.9982925653457642


# Display final model parameter 

After training, print the final learned parameters to see how well the model has learned to approximate the target from the input.

In [73]:
print("Final Model Parameters:", list(model.parameters()))

Final Model Parameters: [Parameter containing:
tensor([1.9992], requires_grad=True)]


for deployment in PyTorch : TorchScript&OnnX is used .