## NUMPY

1. It is a core python library used     for  numerical computation 

2. It is built for handling  large arrays and matrices effeciently.

3. It is faster than python built in lists because it uses c language style storage where actual values are stored at contiguous location (not object references).

## It contain :

**ndarray object**: N-dimensional array for fast numerical operations.

**Vectoriszed operations**: Perform element_wise calculations without loops.

**broadcasting**: Operate on arraya of different shapes

**Linear algebra functions**: Matrix operations like multiplication and inversion 

**Statistical function**: Mean , median , stadard deviation .

**Integration**: Works with Pandas, Scipy and scikit_learn.


## Why to learn numpy 

1. Excutes vectorized operations 10 to 100 times faster than standar Python loops.

2. Uses homogeneous arrays to store large datasets more compactly than python lists.

3. Provide otimized functions for linear algebra, Fourier transforms an matrix manipulations.

4. Includes robust tools for statistics, random number generation and missing data managmenet.

5. Expresses complex math in single-line commands,eliminating the need for manual, nested loops.

## Types of array 

**One dimensional array**





In [2]:
import numpy as np 
a=[1,2,3,4,5,6]
arr= np.array(a)
print("list in python:",a)
print("numy array in python:",arr)



list in python: [1, 2, 3, 4, 5, 6]
numy array in python: [1 2 3 4 5 6]


## Multi-Dimensional Array




In [14]:
import numpy as np 

list_1 =[1,2,3,4,5,6,7,8]
list_2 =[6,4,6,3,6,8,2,4]
list_3 =[2,5,6,7,9,88,4,5]

arr = np.array([list_1,list_2,list_3])
print("numpy multidimensional array:\n",arr)





numpy multidimensional array:
 [[ 1  2  3  4  5  6  7  8]
 [ 6  4  6  3  6  8  2  4]
 [ 2  5  6  7  9 88  4  5]]


## Parameters of Numpy Array

1. **Axis**: Describe the order of the indexing into the array.

Axis 0 = One dimensional
Axis 1 = Two dimensional
Axis 2 = Three dimensional

2. **Shape**: No. of elements along with each axis and is returned as a tuple.


In [21]:
import numpy as np 
arr = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [19,23,34,4,56]])
print("shape of an array:",arr.shape)




shape of an array: (3, 5)


3. **Rank**: no. of axes or dimensions it has.

one dimension array as 1 rank 
two dimension array has 2 rank 

4. **Data type objects(dtype)**: it is an example of numpy.dtype class

It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.



In [22]:
import numpy as np 
arr_1= np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])
print("Data type of an array 1:",arr_1.dtype)

print("Data type of array:",arr_2.dtype)


Data type of an array 1: int64
Data type of array: int64


## Different ways of creating a numpy

**numpy.fromiter()**: create a new one dimensional array from an iterable object.

**Syntax**: numpy.fromiter(iterable,dtype,count=-1)


we can also use generator to create array in numpy .

## Creating a numpy array from unicode 

 You have to use U2 as it represent unicode string with a fixed length of 2 characters 

 ** U indicates that the datatype in unicode and the number '2' specifies the length of each string .

In [20]:
import numpy as np 
a = [1,2,3,4,5,6,7,8,9]
arr = np.fromiter(a,dtype=int)
print(a)

## creating a numpy array generated by generator expression in python 

b=(x**3 for x in range(3))
arr_1 = np.fromiter(b,int)
print(arr_1)

## square of number 0 to 5 

c = (x**2 for x in range(6))
arr_2 = np.fromiter(c, int)
print(arr_2)

# unicode

d =[70,100,100,106]
un = np.fromiter((chr(x) for x in d),dtype='U1')
print(un)

e = "python"
unicode =np.fromiter(e,dtype='U2')
print(unicode)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 8]
[ 0  1  4  9 16 25]
['F' 'd' 'd' 'j']
['p' 'y' 't' 'h' 'o' 'n']
